language: node_js
node_js:
  - 0.10

services:
  - xvfb

before_script:
  - nvm install-latest-npm
  - npm install --quiet -g karma bower
  - bower install
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - node_modules/karma/bin/karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/karma/bin/karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
